services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: admin@123
    volumes:
      - ./mariadb_data:/var/lib/mysql
    networks:
      - wp-network

  wordpress:
    image: wordpress:php8.2-fpm-alpine
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: wordpressdb
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: admin@123
    volumes:
      - ./wordpress_data:/var/www/html
    networks:
      - wp-network
    depends_on:
      - mariadb

networks:
  wp-network:
    name: wp-network