services:
  caddy:
    build: .
    container_name: caddy_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../wordpress_mariadb/wordpress_data:/var/www/html   # share WordPress data
      - ./waf:/etc/caddy/waf              # waf config
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./log:/var/log/caddy  # mount folder log ra host
    networks:
      - wp-network

networks:
  wp-network:
    external: true